app/models.py
from enum import unique
from .auth.models import User, AnonymousUser
from . import db
from datetime import datetime
from sqlalchemy import Column, Integer, BigInteger, Text, String, DateTime

class Company(db.Model):
    """
    The model for the "Company" object/table
    """

    __tablename__ = "companies"

    id = Column(Integer, primary_key=True)
    industry = Column(String(128), index=True)
    name = Column(String(256), index=True, unique=True)
    city = Column(String(128), index=True)
    state = Column(String(128), index=True)
    country = Column(String(128), index=True)
    phone = Column(String(128), unique=True)
    revenue = Column(BigInteger, index=True)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.now)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, ValidationError, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange

class CompanyForm(FlaskForm):
    """
    Form for adding and editing companies.
    """
    name = StringField('Company Name', validators=[DataRequired(), Length(1, 256)])
    industry = StringField('Industry', validators=[DataRequired(), Length(1, 128)])
    city = StringField('City', validators=[DataRequired(), Length(1, 128)])
    state = StringField('State or Province', validators=[DataRequired(), Length(1, 128)])
    country = StringField('Country', validators=[DataRequired(), Length(1, 128)])
    phone = StringField('Phone #', validators=[DataRequired(), Length(min=6)])
    revenue = IntegerField('Monthly Revenue (USD)', validators=[NumberRange(min=0)])
    notes = TextAreaField('Notes')
    submit = SubmitField('Add Company')

app/__init__.py
import os

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from werkzeug.exceptions import HTTPException

# instantiate extensions
login_manager = LoginManager()
db = SQLAlchemy()


def create_app(environment='development'):

    from config import config
    from .views import main_blueprint
    from .auth.views import auth_blueprint
    from .auth.models import User, AnonymousUser

    # Instantiate app.
    app = Flask(__name__)

    # Set app config.
    env = os.environ.get('FLASK_ENV', environment)
    app.config.from_object(config[env])
    config[env].configure(app)

    # Set up extensions.
    db.init_app(app)
    login_manager.init_app(app)

    # Register blueprints.
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(main_blueprint)

    # Set up flask login.
    @login_manager.user_loader
    def get_user(id):
        return User.query.get(int(id))

    login_manager.login_view = 'auth.login'
    login_manager.login_message_category = 'info'
    login_manager.anonymous_user = AnonymousUser

    # Set up migrator
    migrate = Migrate(app, db)

    # Error handlers.
    @app.errorhandler(HTTPException)
    def handle_http_error(exc):
        return render_template('error.html', error=exc), exc.code

    return app

app/views.py
from unicodedata import name
from alembic.config import main

from flask.helpers import flash
from sqlalchemy.orm import query
from app.auth.views import login
from flask import redirect, render_template, Blueprint, request, url_for
from flask_login import current_user, login_required

from . import db

from .forms import CompanyForm
from .models import Company

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def index():
    companies = Company.query.all()
    return render_template('index.html', companies=companies)

@main_blueprint.route('/companies')
def search_companies():
    field = request.args.get('field')
    value = request.args.get('value')
    print(f'field: {field}, value: {value}')
    field_to_filter = {
        'name': Company.query.filter(Company.name.like(f'%{value}%')).all,
        'industry': Company.query.filter(Company.industry.like(f'%{value}%')).all,
        'city': Company.query.filter(Company.city.like(f'%{value}%')).all,
        'state': Company.query.filter(Company.state.like(f'%{value}%')).all,
        'country': Company.query.filter(Company.country.like(f'%{value}%')).all,
        'phone': Company.query.filter(Company.phone.like(f'{value}%')).all,
        'max_revenue': Company.query.filter(Company.revenue <= value).all,
        'min_revenue': Company.query.filter(Company.revenue >= value).all
    }
    filter = field_to_filter.get(field, None)
    if filter is not None:
        companies = filter()
    else:
        companies = Company.query.all()
        flash('Cannot search by this field!', 'warning')
    return render_template('index.html', companies=companies, is_search=True)

@main_blueprint.route('/company/<int:id>', methods=['GET'])
def view_company(id):
    company = Company.query.get_or_404(id)

    return render_template('company.html', company=company)

@main_blueprint.route('/companies/add', methods=['GET', 'POST'])
@login_required
def add_company():
    form = CompanyForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            company = Company(
                name=form.name.data,
                industry=form.industry.data,
                city=form.city.data,
                state=form.state.data,
                country=form.country.data,
                phone=form.phone.data,
                revenue=form.revenue.data,
                notes=form.notes.data
            )
            try:
                db.session.add(company)
                db.session.commit()
                flash("Company successfully added!", "success")
                return redirect(url_for('main.index'))
            except Exception as e:
                print(e)
                db.session.rollback()
                flash('Unable to add company!', 'danger')
    return render_template(
        'add_company.html',
        add_company=True,
        title="Add Company",
        form=form
        )

@main_blueprint.route('/company/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_company(id):
    company = Company.query.get_or_404(id)
    form = CompanyForm(obj=company)
    print(f"id: {id}")
    if request.method == 'GET':
        return render_template(
            'add_company.html',
            add_company=False,
            company=company,
            form=form,
            title="Edit Company"
            )
    elif form.validate_on_submit():
        company.name = form.name.data
        company.industry = form.industry.data
        company.city = form.city.data
        company.state = form.state.data
        company.country = form.country.data
        company.phone = form.country.data
        company.revenue = form.revenue.data
        company.notes = form.notes.data
        try:
            db.session.commit()
            flash("Company successfully edited!", "success")
            return redirect(url_for('main.index'))
        except:
            flash("Unable to edit company!", "danger")

@main_blueprint.route('/company/<int:id>/delete', methods=['GET', 'DELETE'])
@login_required
def delete_company(id):
    company = Company.query.get_or_404(id)
    db.session.delete(company)
    db.session.commit()
    return redirect(url_for('main.index'))

app/templates/_macros.html
<!-- Put your reusable template code into macros here -->

app/templates/add_company.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
  <div class="card w-50 mx-auto">
    <div class="card-header">
      <h4 class="card-title">{{ title }}</h4>
    </div>
    <div class="card-body">
        {% if add_company %}
        <form class="form" role="form" action="{{ url_for('main.add_company') }}" method="post">
        {% else %}
        <form class="form" role="form" action="{{ url_for('main.edit_company', id=company.id) }}" method="post">
        {% endif %}
            <div class="form-group">
            {{form.name.label}}
            {{form.name(class='form-control')}}
            {% for error in form.errors.name %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.industry.label}}
            {{form.industry(class='form-control')}}
            {% for error in form.errors.industry %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.city.label}}
            {{form.city(class='form-control')}}
            {% for error in form.errors.city %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.state.label}}
            {{form.state(class='form-control')}}
            {% for error in form.errors.state %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.country.label}}
            {{form.country(class='form-control')}}
            {% for error in form.errors.country %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.phone.label}}
            {{form.phone(class='form-control')}}
            {% for error in form.errors.phone %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.revenue.label}}
            {{form.revenue(class='form-control')}}
            {% for error in form.errors.revenue %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            <div class="form-group">
            {{form.notes.label}}
            {{form.notes(class='form-control')}}
            {% for error in form.errors.notes %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            {{form.submit(class='btn btn-primary')}}
        </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{{ config.APP_NAME }}</title>
  <!-- meta -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  {% block meta %}{% endblock %}
  <!-- styles -->
  <script src="https://kit.fontawesome.com/72292ae660.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">
  {% block links %}{% endblock %}
</head>

<body>
  <!-- Header -->
  <header>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <!-- Navbar Brand -->
        <a class="navbar-brand" href="{{ url_for('main.index') }}">{{ config.APP_NAME }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <!-- Main Navigation -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#about">About</a>
            </li>
          </ul>
          <!-- Login/Logout -->
          <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userActions" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">{{current_user.username | capitalize}}</a>
              <div class="dropdown-menu" aria-labelledby="userActions">
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- Flash Messages -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismisible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <!-- Main Content -->
  {% block content %}{% endblock %}
  <!-- Footer-->
  <footer>
    <div class="container-fluid bg-light py-5">
      <div class="row py-4">
        <div class="col-lg-10 col-md-6 mb-4 mb-lg-0">
          <h6 id='about' class="text-uppercase font-weight-bold mb-4">About</h6>
          <p class="text-muted">Cataloguing companies since 2020</p>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Quick Links</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="{{ url_for('auth.login') }}" class="text-muted">Login</a></li>
            <li class="mb-2"><a href="{{ url_for('auth.register') }}" class="text-muted">Register</a></li>
          </ul>
        </div>
      </div>
      <!-- Copyrights -->
      <div class="text-center">
        <p class="text-muted mb-0 py-2">&copy;2020 {{ config.APP_NAME }} | All rights reserved.</p>
      </div>
    </div>
  </footer>
  <!-- scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

app/templates/company.html
{% extends "base.html" %}

{% block content %}
<div class="container mb-4">
    <a href="{{ url_for('main.index') }}">&lt; Back to Companies List</a>
    <h1 class="mb-4">{{ company.name }}</h1>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Industry:</strong>
        </div>
        <div class="col-6">
            {{ company.industry }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Industry:</strong>
        </div>
        <div class="col-6">
            {{ company.industry }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>City:</strong>
        </div>
        <div class="col-6">
            {{ company.city }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>State:</strong>
        </div>
        <div class="col-6">
            {{ company.state }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Country:</strong>
        </div>
        <div class="col-6">
            {{ company.country }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Phone #:</strong>
        </div>
        <div class="col-6">
            {{ company.phone }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Revenue (USD):</strong>
        </div>
        <div class="col-6">
            {{ company.revenue }}
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-4">
            <strong>Notes:</strong>
        </div>
        <div class="col-6">
            {{ company.notes }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="mb-4">Companies</h1>
  {% if companies %}
    <div class="row">
      <div class="col">
        <form class="form" role="form" action="{{ url_for('main.search_companies') }}" method="get">
          <label for="field">Search by field:</label>
          <select name="field" id="field">
            <option value="name">Name</option>
            <option value="city">City</option>
            <option value="state">State</option>
            <option value="country">Country</option>
            <option value="phone">Phone</option>
            <option value="max_revenue">Max Revenue</option>
            <option value="min_revenue">Min Revenue</option>
          </select>
          <input type="search" id="field_search" name="value">
          <button type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
    <div class="row">
        <div class="col-lg-3">Name</div>
        <div class="col-lg-3">Industry</div>
        <div class="col-lg-3">Location</div>
        <div class="col-lg-2">Monthly Revenue</div>
    </div>
    <hr>
    {% for company in companies %}
        <div class="row">
            <div class="col-lg-3">{{ company.name }}</div>
            <div class="col-lg-3">{{ company.industry }}</div>
            <div class="col-lg-3">{{ company.city }}, {{ company.state }}, {{ company.country }}</div>
            <div class="col-lg-2">{{ company.revenue }}</div>
            <a href="{{ url_for('main.view_company', id=company.id) }}">
              <i class="fa fa-search"></i>
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('main.edit_company', id=company.id) }}">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="{{ url_for('main.delete_company', id=company.id) }}">
                <i class="fa fa-trash"></i>
            </a>
            {% endif %}
        </div>
    {% endfor %}
  {% endif %}
  {% if current_user.is_authenticated %}
  <hr>
  <div class="row mt-6">
    <div class="col text-center">
      <a href="{{ url_for('main.add_company') }}" class="btn btn-default btn-lg">
        <i class="fa fa-plus"></i>
        Add Company
      </a>
    </div>
    
  </div>
  {% endif %}
</div>
{% endblock %}